spring.application.name=springjwt

# = DATABASE CONFIG (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/istdbangaloreweb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=${DATABASE_PASSWORD}

# = JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# = SERVER
server.port=8088

# = JWT CONFIG
jwt.secret=mysupersecretkeymysupersecretkey
jwt.expiration=86400000