spring.application.name=springjwt

# = DATABASE CONFIG (MySQL)
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

# = JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# = SERVER
server.port=${PORT:8080}

# = JWT CONFIG
jwt.secret=mysupersecretkeymysupersecretkey
jwt.expiration=86400000
